# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dad4399d4045c99cacb152246d06b7c51b2b2bf4c39163151679ce76a93df2af641d14a9e80e7bc171e644be641d78d18eee7cecb3cc4195c0eeee2f7fa0372a

test:
  secret_key_base: 6d75b0149dcbd9da84c98d49867a350d8286e24d0340b4e213b2eeb4bf51385296196ac4f94092d3a50a2ac977e99c3cc86fda094d15b6a723d341bb432e6b53

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
